server:
  port: 8070
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.67.104.142:8848
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: alibaba-wii-service
wii:
  # 异构微服务的IP
  ip: www.baidu.com
  # 异构微服务的端口
  port: 80
  # 异构微服务的健康检查URL
#  health-check-url: http://localhost:8060/health.json